#/usr/bin/env python3
import json
import sys
from lxml.html import parse

s=""" <table data-layout="full-width"><tbody><tr><th><p><strong>№</strong></p></th><th><p><strong>ФИ</strong></p></th><th><p><strong>Направление работы</strong></p></th><th><p><strong>ФИО</strong></p></th><th><p><strong>e-mail</strong></p></th><th><p><strong>IP</strong></p></th><th><p><strong>Мобильный</strong></p></th><th><p><strong>День рождения</strong></p></th><th><p><strong>Login AD</strong></p></th><th><p><strong>Комната</strong></p></th><th><p><strong>Табельный номер</strong></p></th></tr><tr><td><p>1</p></td><td><p>Иванов Леонид</p></td><td><p>Директор ДСМ</p></td><td><p>Иванов Леонид Павлович</p></td><td><p><a href="mailto:t@mt.ru">t@mt.ru</a></p></td><td><p>19</p></td><td><p>79160000000</p></td><td><p>16.окт</p></td><td><p>t</p></td><td><p>3</p></td><td><p /></td></tr><tr><td><p>2</p></td><td><p>Иванов Виталий</p></td><td><p>business teamlead</p></td><td><p>Иванов Виталий Иванович</p></td><td><p>v@mt.ru</p></td><td><p>11</p></td><td><p>79160000000</p></td><td><p>02.авг</p></td><td><p>v</p></td><td><p>3</p></td><td><p>488888</p></td></tr><tr><td><p>3</p></td><td><p>Иванов Ильдар</p></td><td><p>Управление продуктом (сеть)</p></td><td><p>Иванов Ильдар Иванович</p></td><td><p>i@mt.ru</p></td><td><p>10</p></td><td><p>79160000000</p></td><td><p>26.июн</p></td><td><p>i</p></td><td><p>3</p></td><td><p>2388888</p></td></tr><tr><td><p>4</p></td><td><p>Иванов Андрей</p></td><td><p>Управление продуктом (реклама, 360)</p></td><td><p>Иванов Андрей Анатольевич</p></td><td><p>a@mt.ru</p></td><td><p>10</p></td><td><p>79160000000</p></td><td><p>29.май</p></td><td><p>a</p></td><td><p>3</p></td><td><p>2368888</p></td></tr><tr><td><p>5</p></td><td><p>Иванов Алексей</p></td><td><p>Управление продуктом (Гео)</p></td><td><p>Иванов Алексей Александрович</p></td><td><p>aa@mt.ru</p></td><td><p>16</p></td><td><p>79160000000</p></td><td><p>25.май</p></td><td><p>aa</p></td><td><p>3</p></td><td><p>6888888</p></td></tr><tr><td><p>6</p></td><td><p><del>Иванов Иван</del></p></td><td><p><del>Управление продуктом (RA)</del></p></td><td><p><del>Иванов Иван Иванович&nbsp;</del></p></td><td><p>g@mt.ru</p></td><td><p><del>14</del></p></td><td><p><del>79160000000</del></p></td><td><p><del>07.апр</del></p></td><td><p><del>g</del></p></td><td><p><del>уволен</del></p></td><td><p /></td></tr><tr><td><p>7</p></td><td><p>Иванов Антон</p></td><td><p>Управление продуктом (RA)</p></td><td><p>Иванов Антон Геннадьевич</p></td><td><p>ag@mt.ru</p></td><td><p>19</p></td><td><p>79160000000</p></td><td><p /></td><td><p /></td><td><p /></td><td><p /></td></tr></tbody></table> """

table = etree.HTML(s).find("body/table")
rows = iter(table)
headers = [col.text for col in next(rows)]
for row in rows:
    values = [col.text for col in row]
    print (values)